"""added confirmed column

Revision ID: 937168e359f3
Revises: 684388f2053c
Create Date: 2020-08-11 21:33:44.610997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937168e359f3'
down_revision = '684388f2053c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'confirmed')
    # ### end Alembic commands ###
